import React, { useState } from 'react';
import { Bot, Sparkles, Send, Loader2 } from 'lucide-react';
import { getBusinessInsights } from '../services/geminiService';
import { Product, Transaction } from '../types';

interface AiAdvisorProps {
  inventory: Product[];
  transactions: Transaction[];
}

const AiAdvisor: React.FC<AiAdvisorProps> = ({ inventory, transactions }) => {
  const [query, setQuery] = useState('');
  const [response, setResponse] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const predefinedQuestions = [
    "How can I reduce my logistics costs?",
    "Based on my stock, what should I restock?",
    "Explain Escrow to my customers.",
    "Draft a WhatsApp message for late payments."
  ];

  const handleAsk = async (q: string) => {
    setLoading(true);
    setResponse(null);
    setQuery(q);
    
    // Call Gemini Service
    const result = await getBusinessInsights(inventory, transactions, q);
    
    setResponse(result);
    setLoading(false);
  };

  return (
    <div className="h-full flex flex-col pb-20">
      <div className="flex items-center gap-3 mb-6">
        <div className="p-3 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-xl text-white shadow-lg">
          <Bot size={24} />
        </div>
        <div>
          <h2 className="text-2xl font-bold text-slate-800">TradeSync AI</h2>
          <p className="text-slate-500">Your 24/7 Business Consultant.</p>
        </div>
      </div>

      <div className="flex-1 bg-white rounded-2xl border border-slate-100 shadow-sm flex flex-col overflow-hidden">
        <div className="flex-1 p-6 overflow-y-auto">
          {!response && !loading && (
            <div className="h-full flex flex-col justify-center items-center text-center opacity-60">
               <Sparkles size={48} className="text-indigo-400 mb-4" />
               <p className="text-lg font-medium text-slate-700">Ask me anything about your business.</p>
               <p className="text-sm text-slate-500 max-w-xs mt-2">I can analyze your inventory, suggest logistics routes, or help draft customer messages.</p>
            </div>
          )}

          {loading && (
            <div className="flex items-center justify-center h-full">
              <div className="flex flex-col items-center gap-3">
                <Loader2 size={32} className="animate-spin text-indigo-600" />
                <p className="text-sm font-medium text-indigo-600">Thinking...</p>
              </div>
            </div>
          )}

          {response && (
            <div className="animate-in fade-in slide-in-from-bottom-4">
               <div className="bg-slate-100 p-4 rounded-xl rounded-tl-none inline-block mb-4 max-w-[85%]">
                 <p className="text-slate-800 font-medium">{query}</p>
               </div>
               <div className="flex gap-3">
                 <div className="w-8 h-8 rounded-full bg-indigo-100 flex items-center justify-center shrink-0">
                    <Sparkles size={14} className="text-indigo-600" />
                 </div>
                 <div className="space-y-2">
                    <div className="prose prose-sm text-slate-600 bg-indigo-50/50 p-5 rounded-xl rounded-tl-none border border-indigo-100">
                      {response.split('\n').map((line, i) => (
                        <p key={i} className="mb-2 last:mb-0">{line}</p>
                      ))}
                    </div>
                    <p className="text-[10px] text-slate-400">Generated by Gemini. AI can make mistakes.</p>
                 </div>
               </div>
            </div>
          )}
        </div>

        <div className="p-4 border-t border-slate-100 bg-slate-50">
           {/* Quick Chips */}
           <div className="flex gap-2 overflow-x-auto pb-3 mb-2 no-scrollbar">
             {predefinedQuestions.map((q, i) => (
               <button 
                key={i}
                onClick={() => handleAsk(q)}
                className="whitespace-nowrap px-3 py-1.5 bg-white border border-slate-200 rounded-full text-xs font-medium text-slate-600 hover:bg-indigo-50 hover:text-indigo-600 hover:border-indigo-200 transition-colors"
               >
                 {q}
               </button>
             ))}
           </div>

           <div className="flex gap-2">
             <input 
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleAsk(query)}
                placeholder="Type your question..."
                className="flex-1 px-4 py-3 rounded-xl border border-slate-200 focus:outline-none focus:ring-2 focus:ring-indigo-500 shadow-sm"
             />
             <button 
               onClick={() => handleAsk(query)}
               disabled={!query.trim() || loading}
               className="bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 text-white p-3 rounded-xl shadow-md transition-all"
             >
               <Send size={20} />
             </button>
           </div>
        </div>
      </div>
    </div>
  );
};

export default AiAdvisor;